/**
 * Copyright since 2025 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';
import { parseBoolean, parseIntegerWithMin, parsePositiveNumber } from './env-parser';

// The `window.env` object is loaded in the `index.html` file
const loadedEnv = typeof window !== 'undefined' && window.env ? window.env : {};

const base = loadedEnv['fineractApiUrl'];
const provider = loadedEnv['apiProvider'];
const resolvedMinPasswordLength = parseIntegerWithMin(loadedEnv['minPasswordLength'], 1, 8);

export const environment = {
  production: false,
  version: env.mifos_x.version,
  hash: env.mifos_x.hash,
  // For connecting to server running elsewhere update the tenant identifier
  fineractPlatformTenantId: loadedEnv['fineractPlatformTenantId'] || 'default',
  fineractPlatformTenantIds: loadedEnv['fineractPlatformTenantIds'] || 'default',
  // For connecting to others servers running elsewhere update the base API URL
  baseApiUrls:
    loadedEnv['fineractApiUrls'] ||
    'https://demo.mifos.community,https://localhost:8443,' +
      (typeof window !== 'undefined' ? window.location.origin : ''),
  // For connecting to server running elsewhere set the base API URL
  baseApiUrl:
    loadedEnv['fineractApiUrl'] ||
    (loadedEnv['fineractApiUrls']?.length > 0
      ? loadedEnv['fineractApiUrls'].split(',')[0]
      : typeof window !== 'undefined'
        ? window.location.origin
        : ''),
  oauthServerUrl: loadedEnv['oauthServerUrl'] ?? (base && provider ? `${base}${provider}` : ''),
  allowServerSwitch: parseBoolean(loadedEnv['allowServerSwitch'], true) ? 'true' : 'false',
  apiProvider: loadedEnv['apiProvider'] || '/fineract-provider/api',
  apiVersion: loadedEnv['apiVersion'] || '/v1',
  apiActuator: loadedEnv['apiActuator'] || '/fineract-provider',
  serverUrl: '',
  /** Feature flag for Remember Me functionality */
  enableRememberMe: false,
  oauth: {
    enabled: parseBoolean(loadedEnv['oauthServerEnabled'], false),
    serverUrl: loadedEnv['oauthServerUrl'] || '',
    logoutUrl: loadedEnv['oauthServerLogoutUrl'] || '',
    appId: loadedEnv['oauthAppId'] || '',
    authorizeUrl: loadedEnv['oauthAuthorizeUrl'] || '',
    tokenUrl: loadedEnv['oauthTokenUrl'] || '',
    redirectUri: loadedEnv['oauthRedirectUri'] || '',
    scope: loadedEnv['oauthScope'] || ''
  },
  warningDialog: {
    title: 'Warning',
    content:
      'This system is for authorized use only. Unauthorized access will result in possible legal action. By accessing this system, you acknowledge that you are authorized to do so and that all data stored and processed here is confidential.',
    buttonText: 'Close'
  },
  defaultLanguage: loadedEnv['defaultLanguage'] || 'en-US',
  supportedLanguages:
    loadedEnv['supportedLanguages'] || 'cs-CS,de-DE,en-US,es-MX,fr-FR,it-IT,ko-KO,lt-LT,lv-LV,ne-NE,pt-PT,sw-SW',
  defaultFormatDate: loadedEnv['defaultFormatDate'] || '',
  defaultFormatDatetime: loadedEnv['defaultFormatDatetime'] || '',
  preloadClients: parseBoolean(loadedEnv['preloadClients'], true),

  defaultCharDelimiter: loadedEnv['defaultCharDelimiter'] || ',',

  displayBackEndInfo: parseBoolean(loadedEnv['displayBackEndInfo'], true) ? 'true' : 'false',
  displayTenantSelector: parseBoolean(loadedEnv['displayTenantSelector'], true) ? 'true' : 'false',
  /** Production mode - when true, shows minimal hero with only branding at bottom */
  productionMode: parseBoolean(loadedEnv['productionMode'], false),
  tenantLogoUrl: loadedEnv['tenantLogoUrl'] || 'assets/images/default_home.png',
  tenantLogoUrlDark: loadedEnv['tenantLogoUrlDark'] || 'assets/images/white-mifos.png',
  documentationBaseUrl: loadedEnv['documentationBaseUrl'] || 'https://mifosforge.jira.com/wiki',
  // Time in seconds, default 60 seconds
  waitTimeForNotifications: parsePositiveNumber(loadedEnv['waitTimeForNotifications'], 60),
  // Time in seconds, default 30 seconds
  waitTimeForCOBCatchUp: parsePositiveNumber(loadedEnv['waitTimeForCOBCatchUp'], 30),
  session: {
    timeout: {
      idleTimeout: parsePositiveNumber(loadedEnv['sessionIdleTimeout'], 300000) // 5 minutes in milliseconds
    }
  },
  httpCacheEnabled: parseBoolean(loadedEnv['httpCacheEnabled'], false),

  mifosInterbankTransfersApiUrl: loadedEnv['mifosInterbankTransfersApiUrl'] || 'https://apis.mifos.community',
  mifosInterbankTransfersApiProvider: loadedEnv['mifosInterbankTransfersApiProvider'] || '/vnext1',
  mifosInterbankTransfersApiVersion: loadedEnv['mifosInterbankTransfersApiVersion'] || '/v1.0',
  mifosInterbankTransfersEnabled: parseBoolean(loadedEnv['mifosInterbankTransfersEnabled'], false),

  /**
   * Mifos Copilot AI assistant: deployment master switch (level 1 feature flag).
   * Off by default; set MIFOS_ENABLE_COPILOT=true to load the panel for a deployment.
   * When off, the panel never renders and its lazy chunk is never downloaded.
   */
  enableCopilot: parseBoolean(loadedEnv['enableCopilot'], false),
  /** Base URL of the Mifos MCP server the Copilot talks to. */
  copilotMcpBaseUrl: loadedEnv['copilotMcpBaseUrl'] || 'https://ai.mifos.community',

  /** Remittance Module Integration (off by default) */
  mifosRemittanceApiUrl: loadedEnv['mifosRemittanceApiClientUrl'] || '',
  mifosRemittanceApiProvider: loadedEnv['mifosRemittanceApiProvider'] || '',
  mifosRemittanceApiVersion: loadedEnv['mifosRemittanceApiVersion'] || '',
  mifosRemittanceEnabled: parseBoolean(loadedEnv['mifosRemittanceEnabled'], false),
  mifosRemittanceApiHeader: loadedEnv['mifosRemittanceApiClientHeader'] || '',
  mifosRemittanceApiKey: loadedEnv['mifosRemittanceApiClientKey'] || '',

  /**
   * Postal Code Lookup — auto-fill city/state/country from postal code (off by default).
   * Uses external Zippopotam.us API. Disable for deployments with strict privacy requirements.
   */
  enablePostalCodeLookup: parseBoolean(loadedEnv['enablePostalCodeLookup'], false),

  minPasswordLength: resolvedMinPasswordLength,
  passwordRegex:
    loadedEnv['passwordRegex'] ||
    `^(?!.*(.)\\1)(?!.*\\s)(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[^\\w\\s]).{${resolvedMinPasswordLength},50}$`,

  /**
   * External National ID System Integration (off by default)
   * When enabled, client creation/editing will lookup external National ID
   * and auto-fill client details (name, DOB, gender) from the external system.
   */
  enableExternalNationalIdSystem: parseBoolean(loadedEnv['enableExternalNationalIdSystem'], false),
  externalNationalIdSystemUrl: loadedEnv['externalNationalIdSystemUrl'] || '',
  externalNationalIdSystemApiHeader: loadedEnv['externalNationalIdSystemApiHeader'] || '',
  externalNationalIdSystemApiKey: loadedEnv['externalNationalIdSystemApiKey'] || '',
  externalNationalIdRegex: loadedEnv['externalNationalIdRegex'] || '',

  /**
   * Hide client data information (mask client names with *)
   * Set via MIFOS_COMPLIANCE_HIDE_CLIENT_DATA env var
   */
  complianceHideClientData: parseBoolean(loadedEnv['complianceHideClientData'], false),

  /**
   * Enable permission-aware UI visibility for menus and buttons.
   * This is a presentation control only; Fineract/server-side authorization remains authoritative.
   * When disabled (default), shows all menus/buttons for backward compatibility
   * Set via MIFOS_PRODUCTION_MODE_ENABLE_RBAC env var
   */
  productionModeEnableRBAC: parseBoolean(loadedEnv['productionModeEnableRBAC'], false),

  OIDC: {
    // Support legacy FINERACT_PLUGIN_OIDC_* variable names for backward compatibility
    oidcServerEnabled:
      parseBoolean(loadedEnv['oidcServerEnabled'], false) || loadedEnv['FINERACT_PLUGIN_OIDC_ENABLED'] === 'true',
    oidcBaseUrl: loadedEnv['oidcBaseUrl'] || loadedEnv['FINERACT_PLUGIN_OIDC_BASE_URL'] || '',
    oidcClientId: loadedEnv['oidcClientId'] || loadedEnv['FINERACT_PLUGIN_OIDC_CLIENT_ID'] || '',
    oidcApiUrl: loadedEnv['oidcApiUrl'] || loadedEnv['FINERACT_PLUGIN_OIDC_API_URL'] || '',
    oidcFrontUrl: loadedEnv['oidcFrontUrl'] || loadedEnv['FINERACT_PLUGIN_OIDC_FRONTEND_URL'] || ''
  }
};

// Server URL
environment.serverUrl = `${environment.baseApiUrl}${environment.apiProvider}${environment.apiVersion}`;
